<a href="https://colab.research.google.com/github/akshithasamudrala9515/TASK_TNSIF_AI-ML/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NUMPY**

NumPy is a powerful open-source Python library used for numerical computing.

Supports:
Multidimensional arrays
Mathematical operations on arrays
Linear algebra
Fourier transforms
Random number generation

Why is NumPy faster than Python lists?

Uses optimized C libraries internally.

In [2]:
import numpy as np

arr1 = [1, 2, 3, 4]
print(arr1)

arr2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
print(arr2)

arr3 = np.array([1, 2, 3])
print(arr3)

arr4 = np.arange(0, 20, 2)
print(arr4)


[1, 2, 3, 4]
[[1, 2, 3, 4], [5, 6, 7, 8]]
[1 2 3]
[ 0  2  4  6  8 10 12 14 16 18]


In [4]:
#Zeros Array
zero = np.zeros((3, 3))
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
#Ones Array
one = np.ones((3, 3))
print(one)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
#Identity Matrix
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
#Linspace
ls = np.linspace(2, 10, 5)
print(ls)

[ 2.  4.  6.  8. 10.]


In [10]:
#Random Numbers
randnum = (np.random.rand(2, 3) * 10).astype(int)
print(randnum)

[[7 4 4]
 [7 5 5]]


In [11]:
#Sum, Mean and Standard Deviation
array1 = [[1, 2, 3, 4],
          [5, 6, 7, 8]]

array2 = [[4, 6, 8, 3],
          [2, 5, 7, 9]]

add = np.sum(array2)
print(add)

mean = np.mean(array1)
print(mean)

std = np.std(array1)
print(std)

44
4.5
2.29128784747792


In [13]:
#Minimum, Maximum, Argmin and Argmax
Min = np.min(array1)
print(Min)

Max = np.max(array1)
print(Max)

ArgMin = np.argmin(array1)
print(ArgMin)

ArgMax = np.argmax(array1)
print(ArgMax)

1
8
0
7


In [14]:
#Matrix Multiplication
x = np.array([[3, 4],
              [5, 6]])

y = np.array([[8, 9],
              [6, 7]])

dot = np.dot(x, y)
print(dot)

[[48 55]
 [76 87]]


In [15]:
#Sorting
sorts = np.sort(array2)
print(sorts)

[[3 4 6 8]
 [2 5 7 9]]


**TASKS**

In [16]:
#1. Create a NumPy array containing numbers from 1 to 20 using an inbuilt function.
import numpy as np

array1 = np.arange(1, 21)
print(array1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [17]:
#2. Create an array of all zeros with 10 elements and convert it into a matrix.
import numpy as np

array2 = np.zeros(10)
matrix = array2.reshape(2, 5)

print(matrix)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [18]:
#3. Create an array containing even numbers from 2 to 20.
import numpy as np

array3 = np.arange(2, 21, 2)
print(array3)

[ 2  4  6  8 10 12 14 16 18 20]


In [19]:
#4. Create an array and find its shape, dimensions, data type, size, and multiply every element by 2.
import numpy as np

array4 = np.array([1, 2, 3, 4, 5])

print(array4.shape)
print(array4.ndim)
print(array4.dtype)

mul = array4 * 2
print(mul)

print(array4.size)

(5,)
1
int64
[ 2  4  6  8 10]
5


In [20]:
#5. Create a 1D array and find its sum, mean, minimum, and maximum values.
import numpy as np

array5 = np.array([1, 2, 3, 4, 5, 6])

add = np.sum(array5)
print(add)

avg = np.mean(array5)
print(avg)

Min = np.min(array5)
print(Min)

Max = np.max(array5)
print(Max)

21
3.5
1
6
